### ISSUE TITLE
Index out of range issue

### ISSUE THREAD

**Issue by MadcowD** [ctralie/ripser#23]
Sometimes this happens:
```
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "run_homology_computation.py", line 306, in process_experiment_homology
    raise ef
  File "run_homology_computation.py", line 290, in process_experiment_homology
    diagram = r.fit_transform(Xtouse)
  File "/usr/local/lib/python3.5/dist-packages/ripser/ripser.py", line 119, in fit_transform
    self.transform(X, distance_matrix, metric)
  File "/usr/local/lib/python3.5/dist-packages/ripser/ripser.py", line 95, in transform
    dgm = self._compute_rips(X)
  File "/usr/local/lib/python3.5/dist-packages/ripser/ripser.py", line 141, in _compute_rips
    n_classes = int(res[0])
IndexError: list index out of range
"""

```

**Comment by MadcowD** [comment]
Happens for rips complexes of two points ( with maxdim set to 1). 

I suspect its just that 2 points is obviously to little to build a 2-simplex and this edge case was not handled.

**Comment by ctralie** [comment]
Well spotted thank you, I will take a look as soon as I can!

**Comment by ctralie** [comment]
Hi,
The most recent commit of the sparsedm branch 9893ca6 should fix this.  Checkout ripser, then git checkout sparsedm.   Then python setup.py install.  Let me know if that fixed it.
Thanks,
Chris

**Comment by ctralie** [comment]
@MadcowD let me know if this fixed it
Best,
Chris
